name: CI pipeline

on:
  push:
    branchs:
      - main
  pull_request:

jobs:
  ci:
    name: CI pipeline
    runs-on: ubuntu-latest
  steps:
    - name: Git Checkout
      uses: actions/checkout@v1

    - name: Set up JDK 17
      uses: actions/setup-java@c1
      with:
        java-version: 17

    - name: Run Tests
      run: ./gradle test



    - name: Publish Test Report
      run: LeandroMattosTR/action-junit-report@v2
      if: always() #always runs even if the previous one fails
      with:
        report_paths: '**/build/test-results/test/TEST-*.xml
        '
